config/routes.rb
BCapp::Application.routes.draw do
  resources :users
  resources :posts
  resources :sessions, only: [:new, :create, :destroy]

  root :to => 'posts#index'

  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/admin', to: 'static_pages#home'
  match '/about', to: 'static_pages#about'

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :body, :title, :picture
  has_attached_file :picture, AppConfig.paperclip

  belongs_to :user
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  email           :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  password_digest :string(255)
#  remember_token  :string(255)
#  admin           :boolean          default(FALSE)
#

class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation
  has_secure_password

  before_save { |user| user.email = user.email.downcase }
  before_save :create_remember_token

  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  validates :password, length: {minimum: 6}
  validates :password_confirmation, presence: true

  has_many :posts

  private

  def create_remember_token
    self.remember_token = SecureRandom.urlsafe_base64
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

def new
  @post = Post.new
end

def create
  @post = Post.new(params[:post])
  if @post.save
    flash[:success] = "#{@post.title} successfully saved"
    redirect_to user_path(current_user)
  else
    flash[:error] = "failed"
    render 'new'
  end
end

def show
  @post = Post.find_by_id(params[:id])
  @posts = Post.all.sample(3)
  render :layout => 'public'
end

def edit
  @post = Post.find_by_id(params[:id])
end

def update
  @post = Post.find_by_id(params[:id])
  if @post.update_attributes(params[:post])
    flash[:success] = "Account settings updated"
    redirect_to current_user
  else
    render 'edit'
  end
end

def index
  @posts = Post.all.sort_by { |post| post.created_at }.reverse
  @heroPost = @posts[0]
  render :layout => 'public'
end

def destroy
  @post = Post.find(params[:id])
  @title = @post.title
  if @post.destroy
    flash[:success] = "successfully destroyed #{@title}"
    redirect_to user_path(current_user)
  else
    flash[:error] = "could not destroy"
    redirect_to user_path(current_user)
  end
end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

def new

end

def create
  user = User.find_by_email(params[:session][:email])
  if user && user.authenticate(params[:session][:password])
    sign_in(user)
    redirect_to user
  else
    flash.now[:error] = "Invalid email/password combination"
    render 'new'
  end
end

def destroy
  sign_out
  redirect_to root_path
end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

def home

end

def about
  render :layout => 'about'
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, :only => [:index, :edit, :destroy]
  before_filter :correct_user,   :only => [:edit, :update]
  before_filter :admin_user,     :only => [:destroy, :new]

def new
  @user = User.new
end

def create
  @user = User.new(params[:user])
  if @user.save
    sign_in @user
    flash[:success] = "You registered!"
    redirect_to home_path
  else
    render 'new'
  end
end

def show
  if User.find_by_id(params[:id])
    @user = User.find_by_id(params[:id])
    @posts = Post.all.sort_by { |post| post.created_at }.reverse
  else
    flash[:error] = "not a real user"
    redirect_to home_path
  end
end

def edit
end

def update
  if @user.update_attributes(params[:user])
    sign_in @user
    flash[:success] = "Account settings updated"
    redirect_to @user
  else
    render 'edit'
  end
end

def index
  @users = User.all
end

def destroy
  @user = User.find_by_id(params[:id])
  @user.destroy
  flash[:success] = "#{@user.name} has been deleted"
  redirect_to root_path
end

  private

    def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_path, notice: "Please sign in."
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to root_path unless current_user?(@user)
    end

    def admin_user
      redirect_to root_path unless current_user.admin?
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def controller?(*controller)
    controller.include?(params[:controller])
  end

  def action?(*action)
    action.include?(params[:action])
  end

  def javascript(*files)
    content_for(:head) { javascript_include_tag(*files) }
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end
  def signed_in?
    !current_user.nil?
  end
  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end

  def current_user?(user)
    current_user == user
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  def store_location
    session[:return_to] = request.fullpath
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/about.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Brandon's Blog</title>
    <%= stylesheet_link_tag    "header" %>
    <%= stylesheet_link_tag    "about" %>
    <link href="//netdna.bootstrapcdn.com/font-awesome/3.1.0/css/font-awesome.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Roboto+Condensed:400,700' rel='stylesheet' type='text/css'>
    <%= javascript_include_tag "application" %>
    <%= yield(:head) %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'shared/public_header' %>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BCapp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container-fluid">
<%= render 'shared/header' %>

  <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>">
        <%= value %>
      </div>
    <% end %>

  <%= yield %>
  <%= debug(params) if Rails.env.development? %>
</div>

</body>
</html>

app/views/layouts/public.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Brandon's Blog</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <link href='http://fonts.googleapis.com/css?family=Roboto+Condensed:400,700' rel='stylesheet' type='text/css'>
    <%= javascript_include_tag "application" %>
    <%= yield(:head) %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'shared/public_header' %>
    <%= yield %>
    <%= render 'shared/public_footer' %>
  </body>
</html>

app/views/posts/edit.html.erb
<div class="row">
  <div class="span6 offset3">
  <%= render 'shared/error_messages', object: @post %>
  <%= form_for (@post) do |f| %>
    <%= f.label :title %>

    <%= f.text_field :title %>
    <%= f.label :body %>
    <%= f.text_area :body, class: "post-input-field"  %>

    <%= @post.picture.url %>
    <%= f.file_field :picture %>
    <br>
    <%= f.submit "Submit Post", class: "btn btn-large btn-success" %>
  <% end %>
  </div>
</div>

app/views/posts/index.html.erb
<% javascript 'homepage' %>
<div id="homepagecontainer">
<div class="hero-post-container">
  <h1>Latest Post</h1>
  <%= link_to(post_path(@heroPost)) do %>
  <div class="hero-post">
    <div class="hero-post-left">
      <div class="hero-post-left-inner">
        <%= @heroPost.title.html_safe %>
        <br>
        <%= @heroPost.created_at.strftime("%d %b, %Y") %>

      </div>
    </div>
    <div class="hero-post-right">
      <%= image_tag @heroPost.picture.url(:normal) %>
    </div>
  </div>
  <% end %>
  <% if @heroPost.body.length > 1 %>
    <div class="post-body">
      <div class="post-body-inner">
        <%= truncate(@heroPost.body, :length => 1000).html_safe %>
      </div>
    </div>
  <% else %>
    <div class="post-body-quote">
      Bad-ass Quote
    </div>
  <% end %>
  <h1>Older Posts</h1>
  </div>
<div class="card-container">

  <%= render :partial => 'shared/postCard', :object => {:posts => @posts, :latestpost => @heroPost } %>
</div>
  <% if signed_in? %>
  <%= link_to 'admin', current_user %>
  <% end %>
</div>

app/views/posts/new.html.erb
<div class="row">

  <div class="span6 offset3">
    <h1>Make a Post </h1>
    <%= render 'shared/error_messages', object: @post %>
  <%= form_for (@post) do |f| %>
    <%= f.label :title %>

    <%= f.text_field :title %>
    <%= f.label :body %>
    <%= f.text_area :body, value: " ", class: "post-input-field"  %>

    <%= f.file_field :picture %>
    <br>
    <%= f.submit "Submit Post", class: "btn btn-large btn-success" %>
  <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<% javascript 'posts' %>
<div id="post-container">
  <div class="post-inner">

    <% if @post.body.length > 1 %>
    <div class="post-picture">
      <%= image_tag @post.picture.url(:large) %>
    </div>
    <div class="post-overlay">
      <div class="post-date">
        <%= @post.created_at.strftime("%d %b, %Y") %>
      </div>
    </div>

    <% else %>
    <div class="post-picture-quote">
      <%= image_tag @post.picture.url(:large) %>
    </div>
    <div class="post-overlay-quote">
      <div class="post-date">
        <%= @post.created_at.strftime("%d %b, %Y") %>
      </div>
    </div>
    <% end %>

    <div class="post-title">
      <%= @post.title.html_safe %>
    </div>

    <div class="post-body">
      <div class="post-body-inner">
        <%= @post.body.html_safe %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
  <div class="alert alert-error">
    The form contains <%= pluralize(object.errors.count, "error") %>
  </div>
  <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
  </ul>
  </div>
<% end %>

app/views/shared/_header.html.erb
  <div class="row-fluid">
    <div class="span12">
       <div class="navbar navbar-inverse">
        <div class="navbar-inner">
          <%= link_to 'Agnostic App', root_path, class: 'brand' %>
            <ul class="nav pull-right">
            <% if signed_in? %>
              <li><%= link_to 'See all users', users_path %></li>
              <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.name %>
                  <b class="caret"></b>
                  </a>
                  <ul class="downdown-menu">
                    <li><%= link_to 'My profile', current_user %></li>
                    <li><%= link_to 'Signout', signout_path, :method => :delete %></li>
                  </ul>
                </li>

            <% else %>
              <li><%= link_to 'Signin', signin_path %></li>
            <% end %>


            </ul>
        </div>
       </div>
    </div>
  </div>

app/views/shared/_postCard.html.erb
<% postCard[:posts].each do |post| %>
    <% unless post == postCard[:latestpost] %>
      <%= link_to(post_path(post)) do %>
        <div class="post-card">
          <div class="overlay">

          </div>
          <div class="card-title">

            <%= post.title.html_safe %>

          </div>

          <%= image_tag post.picture.url(:normal) %>
          <% if post.body.length > 1 %>
            <div class="date"><%= post.created_at.strftime("%d %b, %Y") %></div>
          <% else %>
            <div class="date"><%= post.created_at.strftime("%d %b, %Y") %></div>
          <% end %>
      <% end %>

          <div class="card-inner">
            <% if post.body.length > 1 %>
            <div class="card-background">
              <%= truncate(post.body, :length => 340).html_safe %>
            </div>
            <% else %>
            <div class="card-background-cardquote">
             <span class="cardquote">Bad-ass Quote</span>
            </div>
            <% end %>
          </div>
        </div>
    <% end %>
<% end %>

app/views/shared/_public_footer.html.erb
<div id="footer-container">
  <div class="footer-inner">
    <div class="footer-inner-right">
      <p>Copyright 2013, All rights reserved (Cause this is obviously worth copying...)</p>
    </div>
  </div>
</div>

app/views/shared/_public_header.html.erb
<div id="header-container">
  <div class="header-inner">
    <div class="header-inner-left">
      <%= link_to root_path do %>
      <div class="headshot">
      </div>
      <h2>Things that make me go hmm...</h2>
      <% end %>

    </div>
    <div class="header-inner-right">
      <%= link_to about_path do %>
        <% if controller?("static_pages") && action?("about") %>
          <div class="header-menu current">
        <% else %>
          <div class="header-menu">
        <% end %>
          <h2>About</h2>
        </div>
      <% end %>
      <%= link_to root_path do %>
        <% if controller?("posts") && action?("index","show") %>
          <div class="header-menu current">
        <% else %>
          <div class="header-menu">
        <% end %>
          <h2>Blog</h2>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/static_pages/about.html.erb
<% javascript 'about' %>
<div id="about-container">
  <a name="hero"/>
  <section class="hero-banner">
    <h1>sup, <span>I'm brandon</span></h1>
    <h2>And this is my blog, where I like to share my thoughts and work.</h2>
    <i class="icon-chevron-sign-down icon-4x"></i>
  </section>
  <a name="who"/>
  <section class="who">
    <h1>my A-type highlights...</h1>
    <div class="who-inner">
      <div class="who-silo">
        <div class="silo-inner" id='pm' >
          <i class="icon-puzzle-piece icon-8x"></i>
          <h2>I'm a product manager &nbsp;<i class="icon-arrow-down"></i></h2>
          <div class="silo-inner-pm">
            <div class="silo-inner-content">
              <p>Currently a PM at<a class="link" href="http://www.freshbooks.com" target="blank"> Freshbooks</a></p>
              <p>Co-founded <a class="link" href="http://www.tunezy.com" target="blank">Tunezy</a> as head of product</p>
            </div>
          </div>
        </div>
      </div>
      <div class="who-silo" >
        <div class="silo-inner"id='fin'>
          <i class="icon-bar-chart icon-8x"></i>
          <h2>I was a finance guy &nbsp;<i class="icon-arrow-down"></i></h2>
          <div class="silo-inner-fin">
            <div class="silo-inner-content">
              <p>3.5 years at Kraft Foods</p>
              <p>CPA, CMA</p>
            </div>
          </div>
        </div>
      </div>
      <div class="who-silo" >
        <div class="silo-inner"id='code'>
          <i class="icon-code-fork icon-8x"></i>
          <h2>I'm learning to code &nbsp;<i class="icon-arrow-down"></i></h2>
          <div class="silo-inner-code">
            <div class="silo-inner-content">
              <table>
                <tr>
                  <th>In prog:</th>
                  <th>On deck:</th>
                </tr>
                <tr>
                  <td>HTML/CSS</td>
                  <td>Android</td>
                </tr>
                <tr>
                  <td>Javascript, JQuery</td>
                  <td>AngularJS</td>
                </tr>
                <tr>
                  <td>Ruby on Rails</td>
                  <td></td>
                </tr>
              </table>
            </div>
          </div>
        </div>
      </div>
      <div class="who-silo" >
        <div class="silo-inner"id='space'>
          <i class="icon-rocket icon-8x"></i>
          <h2>My life goal is to fly to space &nbsp;<i class="icon-arrow-down"></i></h2>
          <div class="silo-inner-space">
            <div class="silo-inner-content">
              <p>Plan A: &nbsp;Make a lot of money</p>
              <p>Plan B: &nbsp;Cost of launches go down</p>
              <p>Plan C: &nbsp;Live for 1000 years</p>
            </div>
          </div>
        </div>
      </div>
    </div>
    <i class="icon-chevron-sign-down icon-4x"></i>
  </section>
  <a name="b-type"/>
  <section class="b-type">
    <h1>...and some b-type</h1>
      <div class="b-type-inner">
      <div class="info">
        <div class="info-inner-one">
          <p>Happily.</p>
          <p>Frosh week sweethearts</p>
          <p>Wife is also a <a class="info-link" href="http://www.theglobeandmail.com/report-on-business/careers/career-advice/from-zero-to-web-programmer-in-nine-weeks/article11684850/" target="blank">risk taker</a></p>
        </div>
      </div>
      <div class="quarter one">
        <p>Married</p>
      </div>
      <div class="quarter two">
        <p>Poker</p>
      </div>
      <div class="info">
        <div class="info-inner-two">
          <p>Played in the <a class="info-link" href="http://en.wikipedia.org/wiki/World_Series_of_Poker" target="blank">WSOP</a></p>
          <p>Built a winning bot algorithm</p>
          <p>Paid for university with winnings</p>
        </div>
      </div>
      <div class="info">
        <div class="info-inner-three">
          <p><a class="info-link" href="http://imgur.com/yjM1ckT" target="blank">Ridin' dirty</a></p>
          <p>Biked to Montreal on Canadian Tire bike</p>
          <p>Bikes got stolen the night we got there</p>
        </div>
      </div>
      <div class="quarter three">
        <p>Cycling</p>
      </div>
      <div class="quarter four">
        <p>Philosophy</p>
      </div>
      <div class="info">
        <div class="info-inner-four">
          <p>"True knowledge exists in knowing <br>that you know nothing."</p>
          <p><a class="info-link" href="http://en.wikipedia.org/wiki/Socrates" target="blank">- Socrates</a></p>
        </div>
      </div>
    </div>
    <i class="icon-chevron-sign-down icon-4x"></i>
  </section>
  <a name="contact"/>
  <section class="contact">
    <h1>Contact</h1>
    <h2><a href="mailto:brandon.mk.chu@gmail.com?Subject=Howdy" target="blank" class="link-contact">Email</a> | <a href="http://ca.linkedin.com/pub/brandon-chu-cma/24/231/71" class="link-contact" target="blank">LinkedIn</a> | <a href="https://twitter.com/BrandonMChu" target="blank" class="link-contact">Twitter</a> | <a href="https://github.com/Brandonmchu" target="blank" class="link-contact">GitHub</a></h2>
    <i class="icon-chevron-sign-up icon-4x"></i>
  </section>
</div>

app/views/static_pages/home.html.erb
<h1>Welcome to the Agnostic App</h1>

<p>This app is a skeleton to make a real web application with.  It has, by default:</p>
<ul>
  <li><strong>Users</strong></li>
  <ul>
    <li>Create, edit, and destroy</li>
    <li>Can view individual and all users</li>
    <li>Admin user type</li>
  </ul>
  <li><strong>Sessions</strong><ul>
    <li>Sign in</li>
    <li>Sign out</li>
    <li>Validations on edit, destroy</li>
  </ul>
  </li>
  <li><strong>UI Frameworks</strong></li>
  <ul>
    <li>Bootstrap (w. sass), this particular one is using flat ui.  To remove flat UI and use normal bootstrap, simply remove "@import 'flat-ui';" from the custom.css.scss file</li>
  </ul>

</ul>

app/views/users/edit.html.erb
<div class="row">
  <div class="span6 offset3">
  <%= render 'shared/error_messages', object: @user %>
  <%= form_for(@user) do |f| %>
    <%= f.label :name %>

    <%= f.text_field :name %>
    <%= f.label :email %>
    <%= f.text_field :email %>


    <%= f.label :password, 'Enter new password' %>
    <%= f.password_field :password %>

    <%= f.label :password_confirmation, 'Confirm' %>
    <%= f.password_field :password_confirmation %>
    <br>
    <%= f.submit "Save Changes", class: "btn btn-large btn-success" %>
  <% end %>
  </div>
</div>

app/views/users/index.html.erb
<% @users.each do |user| %>
  <%= link_to user.name, user_path(user) %> <%= user.email %> <%= link_to 'delete', user, :method => :delete %> <br>
<% end %>

app/views/users/new.html.erb
<div class="row">

  <div class="span6 offset3">
    <h1>Sign Up</h1>
    <%= render 'shared/error_messages', object: @user %>
  <%= form_for(@user) do |f| %>
    <%= f.label :name %>

    <%= f.text_field :name %>
    <%= f.label :email%>
    <%= f.text_field :email, value: " "  %>


    <%= f.label :password %>

    <%= f.password_field :password %>

    <%= f.label :password_confirmation, 'Confirmation' %>
    <%= f.password_field :password_confirmation %>
    <br>
    <%= f.submit "Create my account", class: "btn btn-large btn-success" %>
  <% end %>
  </div>
</div>

app/views/users/profile.html.erb
<%= @user.name %> <%= @user.email %>

app/views/users/show.html.erb
<%= @user.name %> <%= @user.email %>
<%= link_to 'make a new post', new_post_path %>
<table class="admin">
  <th>Created on</th>
  <th>Title</th>
  <th>Edit</th>
  <th>Delete</th>
<% @posts.each do |post| %>
<tr><td><%= link_to post.created_at %></td><td><%= link_to post.title, post_path(post) %></td><td><%= link_to 'edit', edit_post_path(post) %></td><td><%= link_to 'delete', post, :method => :delete %></tr>
<% end %>
</table>